version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_DB: authDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: p
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
